# Generated by Django 4.2.6 on 2023-10-26 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 20, 13, 14, 631086, tzinfo=datetime.timezone.utc)),
        ),
    ]
